
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of requirements.txt
    schedule:
      interval: "daily"
    open-pull-requests-limit: 6
    # Optionally, you can add versioning/ignore rules here.
