
version: "3.8"
services:
  tfserving:
    image: tensorflow/serving:2.14.0
    ports:
      - "8501:8501"   # REST
      - "8500:8500"   # gRPC
    volumes:
      - ./model_repo:/models
    environment:
      - MODEL_NAME=example_tf_model
    command: >
      /usr/bin/tensorflow_model_server
      --port=8500
      --rest_api_port=8501
      --model_base_path=/models/example_tf_model
