
apiVersion: v1
kind: Pod
metadata:
  name: demo-unsigned
  namespace: aegis
  labels:
    app: demo-model-server
spec:
  containers:
    - name: model-server
      image: nginx:stable
      ports:
        - containerPort: 80
  # No initContainer and no cosign-public-key secret mounted -> will be reported by Gatekeeper in dryrun
