
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: alertmanager-source
  namespace: aegis
spec:
  webhook:
    alertmanager:
      endpoint: /alertmanager
      port: "12000"
      method: POST
      url: /alertmanager
      # Optionally add TLS / auth configuration per your cluster
