
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AegisSignedPod
metadata:
  name: require-aegis-signed
spec:
  match:
    # apply to Pod create requests (this will catch pods created by Deployments/StatefulSets)
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    # List the namespaces you want protected. Add "default" or other namespaces you want to enforce.
    namespaces:
      - "aegis"
