
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cosign-public-key
  namespace: aegis
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aegis-vault
    kind: ClusterSecretStore
  target:
    name: cosign-public-key
    creationPolicy: Owner
  data:
    - secretKey: cosign_pub.pem
      remoteRef:
        key: secret/data/aegis/cosign
        property: public_key
