apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegis-api.fullname" . | default "aegis-api" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "aegis-api.name" . | default "aegis-api" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
