{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "aegis-api.fullname" . | default "aegis-api" }}-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: {{ include "aegis-api.fullname" . | default "aegis-api" }}
  updatePolicy:
    updateMode: "{{ .Values.vpa.mode }}"
{{- end }}
